/*
 *  @file  : TestModifyConstGlobalVariable.cpp
 *  @author: luhahua
 *  @date  : 2021-02-14 11:02:18.612
 *  @note  : Generated by SlxTemplates
 */

#include <iostream>

#pragma comment(linker, "/section:.rdata,rw")

using namespace std;

static const volatile size_t gValue = 100;

int main(int argc, char *argv[])
{
    *const_cast<size_t *>(&gValue) = 200;
    cout << gValue << endl;
    return 0;
}