/*
 *  @file  : TestModifyConstGlobalVariable.cpp
 *  @author: luhahua
 *  @date  : 2021-02-14 11:02:18.612
 *  @note  : Generated by SlxTemplates
 */

// https://www.zhihu.com/question/443582514/answer/1729295111

#include <iostream>

// 此链接指令保证全局常量所在的节能够读写，不触发内存写异常
#pragma comment(linker, "/section:.rdata,rw")

using namespace std;

// volatile 保证不将gValue直接优化为100
// 不加volatile的话，可能会导致修改了也没效果
static const volatile size_t gValue = 100;

int main(int argc, char *argv[])
{
    *const_cast<size_t *>(&gValue) = 200;
    cout << gValue << endl;
    return 0;
}